## Q.1 Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

NumPy is a powerful library in Python designed for efficient numerical operations, particularly in scientific computing and data analysis. Its primary purpose is to provide support for handling large datasets and performing mathematical computations with arrays and matrices, offering functionality that enhances Python's native capabilities.

1. **Purpose of NumPy:**

* Array Handling: Provides the ndarray, a fast and flexible multi-dimensional array object for storing data.

* Mathematical Operations: Supplies a wide array of mathematical functions (e.g., linear algebra, statistical operations, Fourier transforms) that operate on arrays and matrices.

* Data Manipulation: Enables easy reshaping, slicing, and broadcasting of arrays, allowing complex manipulations with concise syntax.

* Interfacing: Acts as a foundation for other libraries like SciPy and pandas, providing a common data structure for scientific computing.

2. **Advantages of NumPy:**
* Speed: NumPy arrays are implemented in C, making operations on them significantly faster compared to Python lists, especially for large datasets.

*  NumPy arrays require less memory than Python lists by storing data in a compact, contiguous block of memory.

* Vectorization: Enables operations to be applied element-wise to entire arrays without the need for explicit loops, improving both readability and performance.

* Broad Functionality: Offers a rich ecosystem for numerical computation, including tools for random number generation, matrix operations, and mathematical modeling.

* Interoperability: Can easily interface with data from other languages (e.g., C, C++, and Fortran) and supports efficient integration with other Python libraries.




**NumPy's capabilities significantly enhance Python's capabilities for numerical operations by:**

* Providing efficient data structures for handling large numerical datasets

* Offering a comprehensive set of functions for mathematical operations, linear algebra, and other numerical tasks

* Integrating seamlessly with other scientific Python libraries

* Improving memory efficiency and performance

* Supporting a wide range of applications

* Benefiting from a large and active community

## Q 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

Both `np.mean()` and `np.average()` are used to calculate the mean (average) of a NumPy array. However, they have subtle differences in their behavior.

`np.mean()`

* Direct calculation: Calculates the arithmetic mean directly.
* Weights not supported: Doesn't allow for weighted averages.

`np.average()`
* Weighted averages: Can calculate weighted averages by specifying weights.
* Returns: Returns the weighted average by default.
* Returns mean if no weights: If no weights are provided, it returns the arithmetic mean.

When to Use:
* Use `np.mean()` when every number in your array is equally important.
* Use `np.average()` when some numbers are more important, and you want that reflected in the result (through weights).

In [1]:
# example
import numpy as np

data = np.array([1, 2, 3, 4])

# Unweighted mean
mean = np.mean(data)
print("Mean:", mean)  # Output: 2.5

data = [1, 2, 3, 4]
weights = [1, 2, 3, 4]  # These weights mean '4' is more important
avg = np.average(data, weights=weights) 
print("avarage:",avg)


Mean: 2.5
avarage: 3.0


## Q 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

In NumPy, arrays can be reversed along different axes using several methods. Below are common techniques to reverse a NumPy array along different axes:

1. Using Slicing : ([::-1])

In [2]:
# 1D Array : In a 1D array, you can reverse the entire array using slicing.

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
rev_arr = arr[::-1]
print(rev_arr)  # Output: [5 4 3 2 1]

print("================")

# 2D Array : For a 2D array, you can reverse it along a specific axis (rows or columns) by slicing the appropriate axis.

# Reverse rows (axis 0): 

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_rows = arr_2d[::-1, :]
print(reversed_rows)
# Output:
# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]

print("================")
# Reverse columns (axis 1):

reversed_columns = arr_2d[:, ::-1]
print(reversed_columns)
# Output:
# [[3 2 1]
#  [6 5 4]
#  [9 8 7]]



[5 4 3 2 1]
[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]


2. Using `np.flip()`:

`np.flip()` reverses an array along a specified axis. It is a more flexible method than slicing, allowing you to specify the axis explicitly.

In [3]:
# 1D Array : By default, np.flip() flips the array along its only axis.

flipped_arr_1d = np.flip(arr)
print(flipped_arr_1d)  # Output: [5 4 3 2 1]

print("==============")

# 2D Array : For 2D arrays, you can flip along different axes:

# Flip along rows (axis 0): 

flipped_rows = np.flip(arr_2d, axis=0)
print(flipped_rows)
# Output:
# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]
print("==============")

# Flip along columns (axis 1): 
flipped_columns = np.flip(arr_2d, axis=1)
print(flipped_columns)

# Output:
# [[3 2 1]
#  [6 5 4]
#  [9 8 7]]


[5 4 3 2 1]
[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]


3. Using `np.fliplr()` and `np.flipud()`

These functions are specific to 2D arrays and higher dimensions:

* `np.fliplr()`: Flips the array left to right (i.e., along columns).

* `np.flipud()`: Flips the array upside down (i.e., along rows).


In [4]:
flip_lr = np.fliplr(arr_2d)

flip_ud = np.flipud(arr_2d)



flip_lr , flip_ud


# Output: flip_lr
# [[3 2 1]
#  [6 5 4]
#  [9 8 7]]

# Output: flip_ud
# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]


(array([[3, 2, 1],
        [6, 5, 4],
        [9, 8, 7]]),
 array([[7, 8, 9],
        [4, 5, 6],
        [1, 2, 3]]))

4. Using `np.rot90()`:

For 2D arrays, you can use `np.rot90()` to rotate the array in multiples of 90 degrees, which can be considered a form of reversing in certain cases.




In [5]:
rotated_90 = np.rot90(arr_2d)
rotated_90
# Output:
# [[3 6 9]
#  [2 5 8]
#  [1 4 7]]


array([[3, 6, 9],
       [2, 5, 8],
       [1, 4, 7]])

## Q. 4 How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

To determine the data type of elements in a NumPy array, you can use the `dtype` attribute. 
This attribute returns a NumPy data type object that describes the type of elements stored in the array.

In [6]:
# Example 

import numpy as np

# Creating a NumPy array
arr = np.array([1, 2, 3, 4])

# Determining the data type
print(arr.dtype)  # output: int64 (for example)


# You can also check the data type of a specific element in the array using the type() function:
print(type(arr[0]))  # Output: <class 'numpy.int64'>



int64
<class 'numpy.int64'>


Importance of Data Types in Memory Management and Performance 

1. Memory Management:
The data type affects how much memory each element takes:

* Smaller types (like int8) use less memory.
* Larger types (like int64) use more memory, but they can store bigger numbers.

Example:

* If you use int32, each number takes 4 bytes.
* If you use int64, each number takes 8 bytes.
Choosing the right data type helps save memory, especially when working with large arrays.

2. Speed and Performance :
* Smaller data types (like `float32`) make calculations faster because the computer processes smaller amounts of data.
* Larger data types (like `float64`) are slower, but they give you more precision for complex calculations.

Example:

If your data doesn't need high precision, using float32 instead of float64 can make the code run faster and use less memory.

3. Precision and Accuracy:
Data types also control how accurate your numbers are:

* `float32` is faster but less precise.
* `float64` is slower but more precise.

If you’re doing simple calculations, `float32` is usually enough. For high-precision tasks, like scientific calculations, `float64` is better.

4. Hardware Optimization :

Computers can process many numbers at once (in parallel), but this works best with smaller data types like `int8` or `float32`. Choosing the right type can speed up operations by taking advantage of hardware optimizations.




## Q. 5 Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?


In NumPy, an `ndarray` (n-dimensional array) is a powerful data structure that holds elements of the same type in a grid-like structure.
It can represent multi-dimensional arrays (like 1D, 2D, or even higher dimensions).

In [7]:
import numpy as np

# 1D ndarray (array)
arr_1d = np.array([1, 2, 3, 4])

# 2D ndarray (matrix)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# printing the ndarray
arr_1d , arr_2d


(array([1, 2, 3, 4]),
 array([[1, 2, 3],
        [4, 5, 6]]))

**Key Features of `ndarray` :**

1. Homogeneity: All elements within an ndarray must be of the same data type (e.g., int, float, bool). This ensures efficient memory management and optimized operations.

2. N-dimensional: ndarray can have multiple dimensions (1D, 2D, 3D, etc.), allowing you to represent complex data structures like matrices, tensors, etc.


    * 1D Array (Vector): np.array([1, 2, 3])
    * 2D Array (Matrix): np.array([[1, 2], [3, 4]])
    * 3D Array (Tensor): np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

3. Fixed Size: Once created, the size of an ndarray cannot be changed (though you can create a new one with a different size).

4. Fast Operations: NumPy provides vectorized operations, meaning you can perform element-wise operations on arrays much faster than Python loops.

5. Memory Efficient: NumPy arrays use less memory than Python lists because they store elements of the same type in a contiguous block of memory.

6. Broadcasting: NumPy allows operations on arrays of different shapes, automatically adjusting the shapes when possible (broadcasting). This is very useful for mathematical operations.

**Differences from Standard Python Lists:**
* Homogeneity: Unlike Python lists, which can contain elements of different data types, ndarrays require all elements to be of the same type.
* Performance: NumPy ndarrays are generally much faster than Python lists for numerical operations due to their optimized implementation and vectorized nature.
* Fixed Size: Python lists are dynamic and can be resized on the fly, while ndarrays have a fixed size.
* Memory Efficiency: ndarrays are typically more memory-efficient than Python lists, especially for large arrays.
* Specialized Operations: NumPy provides a rich set of functions and operations specifically designed for working with numerical arrays, which are not available for Python lists.

## Q. 6 Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.


When dealing with large-scale numerical operations, NumPy arrays offer significant performance advantages over standard Python lists. This is primarily due to the following factors:

1. Homogeneity and Memory Efficiency:

    * Data Type Consistency: NumPy arrays store elements of the same data type, ensuring efficient memory usage and optimized operations.

    * Contiguous Memory Allocation: Unlike Python lists, which can store elements of different types and may have gaps in memory, NumPy arrays allocate memory contiguously, allowing for faster access and manipulation.

2. Vectorized Operations:

    * Element-wise Operations: NumPy operations are typically vectorized, meaning they are performed on entire arrays rather than individual elements. This eliminates the need for explicit loops and significantly improves performance.

    * Optimized Code: NumPy leverages highly optimized C code for many of its operations, resulting in substantial speedups compared to Python's interpreted code.

3. Broadcasting:

    * Automatic Shape Adjustment: NumPy's broadcasting mechanism allows arrays of different shapes to be combined in arithmetic operations, simplifying code and reducing the need for explicit shape manipulation.

    * Efficient Calculations: Broadcasting often leads to more efficient calculations by avoiding unnecessary data copying or reshaping.

4. Specialized Functions:

    * Optimized Algorithms: NumPy provides a rich set of specialized functions for numerical operations, such as linear algebra, Fourier transforms, and random number generation. These functions are often implemented using efficient algorithms, further enhancing performance.

5. NumPy's Internal C Implementation:

    * Low-Level Optimization: NumPy's core operations are implemented in C, providing direct access to system memory and avoiding the overhead of Python's interpreter.

    * Optimized Data Structures: NumPy's internal data structures are designed for efficient numerical computations, minimizing memory access and reducing computational overhead.

## Q . 7  Compare `vstack()` and `hstack()` functions in NumPy. Provide examples demonstrating their usage and output.

**Comparison of `vstack()` and `hstack()` in Numpy :**

In NumPy, `vstack()` and `hstack()` are functions used to combine arrays along different axes:

* `vstack()`: Vertically stacks arrays (along the row axis). It stacks arrays one on top of the other.
* `hstack()`: Horizontally stacks arrays (along the column axis). It stacks arrays side-by-side.

**Usage :**
* `vstack()`: Stacks the arrays vertically, turning the 1D arrays into a 2D array where each input array becomes a row.
* `hstack()`: Stacks the arrays horizontally, combining them into a single 1D array where elements from each input array are concatenated side by side.

In [8]:
# example of both hstack() and vstack()

# Creating two 2D array
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

# Example of vsatck()
result_vstack = np.vstack((arr1, arr2))
print("VERTICAL STCK OF 2D ARRAYS :\n",result_vstack)


result_hstack =np.hstack((arr1,arr2))
print("\n Horizontal stack of :\n",result_hstack)

VERTICAL STCK OF 2D ARRAYS :
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

 Horizontal stack of :
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


## Q. 8 Explain the differences between `fliplr()` and `flipud()` methods in NumPy, including their effects on various array dimensions.

In NumPy, the methods fliplr() and flipud() are used to reverse the elements of an array along specific axes.

1. **`fliplr()` (Flip Left-Right) :**

* Purpose: This method flips an array horizontally, meaning it reverses the elements from left to right along axis 1 (the second axis, i.e., columns).


* Effect:

    * For a 2D array, fliplr() reverses the order of the columns, keeping the rows intact.

    * For higher-dimensional arrays (like 3D), it still operates along axis 1, so it flips the elements along the second axis (the columns in 2D planes).

2. **`flipud()` (Flip Up-Down) :**

* Purpose: This method flips an array vertically, meaning it reverses the elements from top to bottom along axis 0 (the first axis, i.e., rows).

* Effect:
    * For a 2D array, flipud() reverses the order of the rows, keeping the columns intact.
    * For higher-dimensional arrays, it still operates along axis 0, flipping the elements along the first axis (the rows in 2D planes).


In [9]:
# Example of fliplr() and flipud()

import numpy as np

# Creating a 2D array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

# Using fliplr() - Flip array 
arr_fliplr = np.fliplr(arr)

# Using flipud() - Flip array
arr_flipud = np.flipud(arr)

# Printing the results
print("Original array:")
print(arr)
#  Output:
# Original array:
# [[1 2 3 4]
#  [5 6 7 8]]

print("\nArray after fliplr:")
print(arr_fliplr)
# output :
# Array after fliplr:
# [[4 3 2 1]
#  [8 7 6 5]]

print("\nArray after flipud:")
print(arr_flipud)
#output :
# Array after flipud:
# [[5 6 7 8]
#  [1 2 3 4]]


Original array:
[[1 2 3 4]
 [5 6 7 8]]

Array after fliplr:
[[4 3 2 1]
 [8 7 6 5]]

Array after flipud:
[[5 6 7 8]
 [1 2 3 4]]


## Q.9 Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

The `array_split()` method in NumPy is a powerful tool for dividing an array into multiple sub-arrays. It takes an array as input and returns a list of sub-arrays. The number of sub-arrays is determined by the `indices_or_sections `argument, which can be either an integer or a sequence of integers.

**Functionality:**

* Input: An array to be split.

* Output: A list of sub-arrays.

* `indices_or_sections` argument:
    * If it's an integer, the array is split into that number of sub-arrays of approximately equal size.

    * If it's a sequence of integers, the sequence specifies the indices where the array should be split.


**Handling Uneven Splits:**

* When the array cannot be evenly divided into the specified number of sub-arrays, `the array_split()` method handles it intelligently.

* The extra elements are distributed among the sub-arrays in a way that ensures the sub-arrays are as close to equal size as possible.

* The first sub-array will be larger than the others if the remainder is not evenly divisible by the number of sub-arrays.

In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Split into 3 sub-arrays
result1 = np.array_split(arr, 3)
print(result1) 
# output : [array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]


# Split at indices 2 and 5
result2 = np.array_split(arr, [2, 5])
print(result2)
# output : [array([1, 2]), array([3, 4, 5]), array([6, 7, 8])]

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]
[array([1, 2]), array([3, 4, 5]), array([6, 7, 8])]


## Q.10  Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?


Vectorization and Broadcasting in NumPy are key concepts that contribute to efficient array operations, making computations faster and more concise. Here's an explanation of both:

**1. Vectorization:**

* Definition: Vectorization refers to performing operations on entire arrays (or large chunks of them) without explicit loops. Instead of processing elements one by one, operations are applied to entire arrays at once.

* Efficiency: It leverages low-level optimizations and compiled code  to perform these operations quickly, making them much faster than traditional Python loops.


In [11]:
# Example : elements wise addition

import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise addition (vectorized)
c = a + b
# printing the value of "c"
c  # Output: [5, 7, 9]

array([5, 7, 9])

**2. Broadcasting :**

* Definition: Broadcasting refers to how NumPy handles arrays with different shapes during arithmetic operations. It "stretches" the smaller array along one or more axes to match the shape of the larger array, without actually copying data.

* Efficiency: Broadcasting allows you to perform operations between arrays of different shapes without needing to manually replicate or resize them, reducing memory usage and improving performance.

* Rules: Broadcasting works when dimensions of arrays are compatible, either:

    * The dimensions are equal.
    * One of the dimensions is 1 (allowing expansion).

In [12]:
# Example: Adding a scalar to a 1D array:

a = np.array([1, 2, 3])

# Broadcasting the scalar 5 to each element in array 'a'
b = a + 5
print("The result is : ", b)  # Output: [6, 7, 8]


# Adding a 1D array to a 2D array: 

x = np.array([[1, 2, 3],[4, 5, 6]])

y = np.array([10, 20, 30])

# Broadcasting y across each row of x
z = x + y
print("\nThe result is : \n",z)
# Output:
# [[11 22 33]
#  [14 25 36]]


The result is :  [6 7 8]

The result is : 
 [[11 22 33]
 [14 25 36]]


**Contributions to Efficient Array Operations:**

* No explicit loops: Both vectorization and broadcasting eliminate the need for writing loops, which in Python can be slow. This results in more concise and readable code.
* Memory efficiency: Broadcasting performs operations without creating unnecessary copies of arrays, leading to lower memory consumption.
* Speed: Vectorized operations are optimized to use underlying C or Fortran libraries, making them significantly faster than element-wise Python loops.