## Q.1 Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.


In [1]:
# Ans

import numpy as np
# creating the array with random integers between 1 to 100
arr1 = np.random.randint(1 , 100 , (3,3)) 
print("The 3x3 array is:\n",arr1) # printing the array

# Interchanging the its rows and columns (Transposd array)
arr2 = arr1.T
print("The Transposed array is :\n", arr2)


The 3x3 array is:
 [[71 61 76]
 [60  5 70]
 [97 83 26]]
The Transposed array is :
 [[71 60 97]
 [61  5 83]
 [76 70 26]]


## Q.2 Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.


In [2]:
# Ans:
import numpy as np

# generating a 1D numpy array with 10 element
arr1 = np.arange(1,11)

print("The 1D numpy array with 10 elements: \n",arr1) 

# reshaping the array into a 2x5 array
arr_2x5 = arr1.reshape(2,5)
print("\nThe reshaped 2x5 array is \n",arr_2x5)

# reshaping the array into 5x2 array
arr_5x2 = arr1.reshape(5,2)
print("\nThe again reshaped 5x2 array is: \n",arr_5x2)


The 1D numpy array with 10 elements: 
 [ 1  2  3  4  5  6  7  8  9 10]

The reshaped 2x5 array is 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

The again reshaped 5x2 array is: 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


## Q. 3 Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.


In [3]:
# Ans :

import numpy as np
# Creating  a 4x4 array with random float values
arr = np.random.rand(4,4)
print("The 4x4 array with random float values: \n", arr)

# adding a border of 0s around it and making a 6x6 array
arr_6x6 = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print("\nThe 6x6 array with 0s as borderd is:\n", arr_6x6)


The 4x4 array with random float values: 
 [[0.07817275 0.70182495 0.82492098 0.45385577]
 [0.04718074 0.15439015 0.06048278 0.30428578]
 [0.51751251 0.10985265 0.52009009 0.28540814]
 [0.60643223 0.50022577 0.97672537 0.26899232]]

The 6x6 array with 0s as borderd is:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.07817275 0.70182495 0.82492098 0.45385577 0.        ]
 [0.         0.04718074 0.15439015 0.06048278 0.30428578 0.        ]
 [0.         0.51751251 0.10985265 0.52009009 0.28540814 0.        ]
 [0.         0.60643223 0.50022577 0.97672537 0.26899232 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


##  Q.4 Using NumPy, create an array of integers from 10 to 60 with a step of 5.


In [4]:
# Ans : 
import numpy as np
# creating an array of integers from 10 to 60 with askip value of 5
array = np.arange(10 , 61 , 5)

# printing the array 
print("Array of integers with skip value of 5 , from 10 to 60 :",array)

Array of integers with skip value of 5 , from 10 to 60 : [10 15 20 25 30 35 40 45 50 55 60]


## Q.5 Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations(uppercase, lowercase, title case, etc.) to each element.

In [5]:
# Ans :
import numpy as np

# making a list of given strings
str = ["python", "numpy","pandas"] 

# converting the list into array
str_arr = np.array(str)

# printing the array of strings
print("The original array is :", str_arr)

# transform to upper case
arr_upr = np.char.upper(str_arr)
print("\nThe upper case array is:",arr_upr)

# transforming to lower case
arr_low = np.char.lower(str)
print("\nThe lower case array is:", arr_low)

# transforming to title case 
arr_title = np.char.title(str_arr)
print("\nThe array of title case:",arr_title)

The original array is : ['python' 'numpy' 'pandas']

The upper case array is: ['PYTHON' 'NUMPY' 'PANDAS']

The lower case array is: ['python' 'numpy' 'pandas']

The array of title case: ['Python' 'Numpy' 'Pandas']


## Q.6 Generate a NumPy array of words. Insert a space between each character of every word in the array.


In [6]:
# Ans:
import numpy as np

# creating an array of some words
arr_word = np.array(["Swaraj","Appu", "Data", "World"])
print("The original  array is:", arr_word)

# inserting a space between every character
arr_space = np.char.join(" ",arr_word)
print("\nArray with space:\n",arr_space)

The original  array is: ['Swaraj' 'Appu' 'Data' 'World']

Array with space:
 ['S w a r a j' 'A p p u' 'D a t a' 'W o r l d']


## Q.7 Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.


In [7]:
# Ans :
import numpy as np

# creating two 3x3 numpy array with random value from 1-10
arr1 = np.random.randint(1,10,(2,3))
arr2 = np.random.randint(1,10,(2,3))

# print the two array
print("Array_1 is:\n",arr1)
print("\nArray_2 is:\n",arr2)

# performing element wise operation 
print("\n===Element wise operation===")

# Addition 
add = arr1 + arr2
print("\nAddition:\n ", add)

# subtraction 
sub = arr1 - arr2
print("\nSubtraction:\n", sub)

#multiplication
mult = arr1 * arr2
print("\nMultiplication:\n", mult)

# division
div = arr1 / arr2
print("\nDivision:\n",div)

Array_1 is:
 [[1 4 7]
 [1 7 9]]

Array_2 is:
 [[5 7 4]
 [5 1 8]]

===Element wise operation===

Addition:
  [[ 6 11 11]
 [ 6  8 17]]

Subtraction:
 [[-4 -3  3]
 [-4  6  1]]

Multiplication:
 [[ 5 28 28]
 [ 5  7 72]]

Division:
 [[0.2        0.57142857 1.75      ]
 [0.2        7.         1.125     ]]


## Q.8  Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.


In [8]:
# Ans :
import numpy as np

# creating a 5x5 
identity_mat = np.identity(5)
print("The 5x5 identity matrix is :\n",identity_mat)

# accessing the digonal elements
dig_elm = identity_mat.diagonal()
print("\nThe digonal elements :\n",dig_elm)


The 5x5 identity matrix is :
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

The digonal elements :
 [1. 1. 1. 1. 1.]


## Q.9 Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [9]:
# Ans :

import numpy as np

# creating an array of 100 random integers between 0 to 1000
array = np.random.randint(0,1001, size=100)
array

# Funtion to check the number is prime or not
def is_prime(n):
    if n<= 1:
        return False
    if n<= 3:
        return True
    if n % 2 == 0 or n % 3==0:
        return False
    
    i = 5
    while i * i<= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

# finding and display all the prime number from the array 
prime_no = [n for n in array if is_prime(n)]
print(prime_no)

[np.int32(127), np.int32(449), np.int32(181), np.int32(5), np.int32(761), np.int32(269), np.int32(479), np.int32(467)]


## Q.10 Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages

In [10]:
# Ans :
import numpy as np

# generating a numpy aray of daily temprature for a month (temp range - 25 to 50)

daily_temp = np.random.randint(25, 55, size = 30)

print("Daily temp:\n", daily_temp)

#assuming 5 weeks of days each so reshaping the array
weekly_temp = daily_temp.reshape(5,6)
print("\nWeekly temp:\n", weekly_temp)

# calculating the  weekly averages 

week_temp_avg = np.mean(weekly_temp,axis=1)
print("\nWeekly temperature avg :")
# week_temp_avg
for i in week_temp_avg:
    print("week avg temp",i ,"`C")



Daily temp:
 [45 34 43 43 42 25 31 34 27 52 33 39 32 52 54 46 41 52 28 44 32 29 25 48
 46 29 27 43 36 35]

Weekly temp:
 [[45 34 43 43 42 25]
 [31 34 27 52 33 39]
 [32 52 54 46 41 52]
 [28 44 32 29 25 48]
 [46 29 27 43 36 35]]

Weekly temperature avg :
week avg temp 38.666666666666664 `C
week avg temp 36.0 `C
week avg temp 46.166666666666664 `C
week avg temp 34.333333333333336 `C
week avg temp 36.0 `C
